AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TemplateBucketName:
    Type: String
    Default: awstut-bucket
    
  Prefix:
    Type: String
    Default: saa-01-009
    
  CloudFrontCacheTTL:
    Type: Number
    Default: 0
    
  EnvProd:
    Type: String
    Default: prod
    
  EnvStg:
    Type: String
    Default: stg
    
  LambdaArchitecture:
    Type: String
    Default: arm64
    
  LambdaHandler:
    Type: String
    Default: index.lambda_handler
    
  LambdaRuntime:
    Type: String
    Default: python3.12
  

Resources:
  ProdS3Stack1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-s3-01.yaml"
      Parameters:
        #BucketName: !Sub "${Prefix}-bucket-prod"
        Prefix: !Ref Prefix
        Env: !Ref EnvProd
        
  StgS3Stack1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-s3-01.yaml"
      Parameters:
        #BucketName: !Sub "${Prefix}-bucket-stg"
        Env: !Ref EnvStg
        Prefix: !Ref Prefix
        
  StgCloudFrontStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - StgS3Stack1
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-cloudfront-01.yaml"
      Parameters:
        BucketName: !GetAtt StgS3Stack1.Outputs.BucketName
        #BucketWebsiteURL: !GetAtt S3Stack1.Outputs.BucketWebsiteURL
        BucketRegionalDomainName: !GetAtt StgS3Stack1.Outputs.BucketRegionalDomainName
        CacheTTL: !Ref CloudFrontCacheTTL
        Env: !Ref EnvStg
        Prefix: !Ref Prefix
        #StagingDistributionDnsName: ""
        
  ProdCloudFrontStack1:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ProdS3Stack1
      - StgCloudFrontStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-cloudfront-01.yaml"
      Parameters:
        BucketName: !GetAtt ProdS3Stack1.Outputs.BucketName
        #BucketWebsiteURL: !GetAtt S3Stack1.Outputs.BucketWebsiteURL
        BucketRegionalDomainName: !GetAtt ProdS3Stack1.Outputs.BucketRegionalDomainName
        CacheTTL: !Ref CloudFrontCacheTTL
        Env: !Ref EnvProd
        Prefix: !Ref Prefix
        #StagingDistributionDnsName: !GetAtt StgCloudFrontStack.Outputs.DistributionDomainName
        
  ProdCloudFrontStack2:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ProdCloudFrontStack1
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-cloudfront-02.yaml"
      Parameters:
        Architecture: !Ref LambdaArchitecture
        Handler: !Ref LambdaHandler
        Prefix: !Ref Prefix
        PrimaryDistribution: !GetAtt ProdCloudFrontStack1.Outputs.Distribution
        Runtime: !Ref LambdaRuntime
        StagingDistributionDnsName: !GetAtt StgCloudFrontStack.Outputs.DistributionDomainName
        
  ProdS3Stack2:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ProdCloudFrontStack1
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-s3-02.yaml"
      Parameters:
        BucketArn: !GetAtt ProdS3Stack1.Outputs.BucketArn
        BucketName: !GetAtt ProdS3Stack1.Outputs.BucketName
        Distribution: !GetAtt ProdCloudFrontStack1.Outputs.Distribution
        #DistributionDomainName: !GetAtt CloudFrontStack.Outputs.DistributionDomainName
        #OAI: !GetAtt CloudFrontStack.Outputs.OAI
        #Prefix: !Ref Prefix
        
  StgS3Stack2:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - StgCloudFrontStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-s3-02.yaml"
      Parameters:
        BucketArn: !GetAtt StgS3Stack1.Outputs.BucketArn
        BucketName: !GetAtt StgS3Stack1.Outputs.BucketName
        Distribution: !GetAtt StgCloudFrontStack.Outputs.Distribution
        #DistributionDomainName: !GetAtt CloudFrontStack.Outputs.DistributionDomainName
        #OAI: !GetAtt CloudFrontStack.Outputs.OAI
        #Prefix: !Ref Prefix
        
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-lambda.yaml"
      Parameters:
        Architecture: !Ref LambdaArchitecture
        Handler: !Ref LambdaHandler
        Prefix: !Ref Prefix
        ProdBucketArn: !GetAtt ProdS3Stack1.Outputs.BucketArn
        Runtime: !Ref LambdaRuntime
        StgBucketArn: !GetAtt StgS3Stack1.Outputs.BucketArn
        
  ProdCustomResourceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ProdS3Stack1
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-customresource.yaml"
      Parameters:
        BucketName: !GetAtt ProdS3Stack1.Outputs.BucketName
        #Env: !Ref EnvProd
        #EnvProd: !Ref EnvProd
        #EnvStg: !Ref EnvStg
        FunctionArn: !GetAtt LambdaStack.Outputs.FunctionArn
        #Prefix: !Ref Prefix
        
  StgCustomResourceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - StgS3Stack1
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-customresource.yaml"
      Parameters:
        BucketName: !GetAtt StgS3Stack1.Outputs.BucketName
        #Env: !Ref EnvProd
        #EnvProd: !Ref EnvProd
        #EnvStg: !Ref EnvStg
        FunctionArn: !GetAtt LambdaStack.Outputs.FunctionArn
        #Prefix: !Ref Prefix
