AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BucketName:
    Type: String

  FunctionArn:
    Type: String

    
Resources:
  CustomResource:
    Type: Custom::CustomResource
    Properties:
      BucketName: !Ref BucketName
      ServiceToken: !Ref FunctionArn
