AWSTemplateFormatVersion: 2010-09-09
Parameters:
  BucketName:
    Type: String

  BucketRegionalDomainName:
    Type: String
    
  CacheTTL:
    Type: Number
    
  Env:
    Type: String
    
  Prefix:
    Type: String


Conditions:
  IsProd:
    !Equals
      - !Ref Env
      - prod
    

Resources:
  OAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig:
        Name: !Sub "${Prefix}-${Env}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        #ContinuousDeploymentPolicyId: !If
        #  - IsProd
        #  - !Ref ContinuousDeploymentPolicy
        #  - !Ref AWS::NoValue
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: !Ref BucketName
          ViewerProtocolPolicy: allow-all
          DefaultTTL: !Ref CacheTTL
          MaxTTL: !Ref CacheTTL
          MinTTL: !Ref CacheTTL
        DefaultRootObject: index.html
        Enabled: true
        Origins:
          - DomainName: !Ref BucketRegionalDomainName
            Id: !Ref BucketName
            OriginAccessControlId: !GetAtt OAC.Id
            S3OriginConfig:
              OriginAccessIdentity: ""
        PriceClass: PriceClass_All
        Staging: !If
          - IsProd
          - false
          - true

Outputs:
  Distribution:
    Value: !Ref Distribution
    
  DistributionDomainName:
    Value: !GetAtt Distribution.DomainName
