AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
    
  Env:
    Type: String
    

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Prefix}-${Env}-bucket"
      AccessControl: Private


Outputs:
  BucketArn:
    Value: !GetAtt Bucket.Arn
    
  BucketName:
    Value: !Ref Bucket
    
  BucketRegionalDomainName:
    Value: !GetAtt Bucket.RegionalDomainName
