AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TemplateBucketName:
    Type: String
    Default: awstut-bucket
    
  Prefix:
    Type: String
    Default: saa-01-009
    
  EnvProd:
    Type: String
    Default: prod
    
  EnvStg:
    Type: String
    Default: stg
    
  LambdaArchitecture:
    Type: String
    Default: arm64
    
  LambdaHandler:
    Type: String
    Default: index.lambda_handler
    
  LambdaRuntime:
    Type: String
    Default: python3.12
  

Resources:
  ProdS3Stack1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-s3-01.yaml"
      Parameters:
        Prefix: !Ref Prefix
        Env: !Ref EnvProd
        
  StgS3Stack1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-s3-01.yaml"
      Parameters:
        Env: !Ref EnvStg
        Prefix: !Ref Prefix
        
  StgCloudFrontStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - StgS3Stack1
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-cloudfront.yaml"
      Parameters:
        BucketName: !GetAtt StgS3Stack1.Outputs.BucketName
        BucketRegionalDomainName: !GetAtt StgS3Stack1.Outputs.BucketRegionalDomainName
        Env: !Ref EnvStg
        Prefix: !Ref Prefix
        StagingDistributionDnsName: ""
        
  ProdCloudFrontStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ProdS3Stack1
      - StgCloudFrontStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-cloudfront.yaml"
      Parameters:
        BucketName: !GetAtt ProdS3Stack1.Outputs.BucketName
        BucketRegionalDomainName: !GetAtt ProdS3Stack1.Outputs.BucketRegionalDomainName
        Env: !Ref EnvProd
        Prefix: !Ref Prefix
        StagingDistributionDnsName: !GetAtt StgCloudFrontStack.Outputs.DistributionDomainName
        
  ProdS3Stack2:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ProdCloudFrontStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-s3-02.yaml"
      Parameters:
        BucketArn: !GetAtt ProdS3Stack1.Outputs.BucketArn
        BucketName: !GetAtt ProdS3Stack1.Outputs.BucketName
        Distribution: !GetAtt ProdCloudFrontStack.Outputs.Distribution

  StgS3Stack2:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - StgCloudFrontStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-s3-02.yaml"
      Parameters:
        BucketArn: !GetAtt StgS3Stack1.Outputs.BucketArn
        BucketName: !GetAtt StgS3Stack1.Outputs.BucketName
        Distribution: !GetAtt StgCloudFrontStack.Outputs.Distribution

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-lambda.yaml"
      Parameters:
        Architecture: !Ref LambdaArchitecture
        Handler: !Ref LambdaHandler
        Prefix: !Ref Prefix
        ProdBucketArn: !GetAtt ProdS3Stack1.Outputs.BucketArn
        Runtime: !Ref LambdaRuntime
        StgBucketArn: !GetAtt StgS3Stack1.Outputs.BucketArn
        
  ProdCustomResourceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ProdS3Stack1
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-customresource.yaml"
      Parameters:
        BucketName: !GetAtt ProdS3Stack1.Outputs.BucketName
        FunctionArn: !GetAtt LambdaStack.Outputs.FunctionArn

  StgCustomResourceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - StgS3Stack1
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-customresource.yaml"
      Parameters:
        BucketName: !GetAtt StgS3Stack1.Outputs.BucketName
        FunctionArn: !GetAtt LambdaStack.Outputs.FunctionArn
