AWSTemplateFormatVersion: 2010-09-09

Parameters:
  BucketArn:
    Type: String

  BucketName:
    Type: String
    
  Distribution:
    Type: String


Resources:
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Statement:
          Action:
            - s3:GetObject
          Effect: Allow
          Principal: 
            Service: 
              - cloudfront.amazonaws.com
          Resource: !Sub "${BucketArn}/*"
          Condition: 
            StringEquals:
              AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}"
