AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Bucket:
    Type: String
    
  FSxSecurityGroup:
    Type: String
    
  FSxStorageCapacity:
    Type: Number
    
  FSxSubnet:
    Type: String

  Prefix:
    Type: String


Resources:
  FSxLustre:
    Type: AWS::FSx::FileSystem
    Properties: 
      FileSystemType: LUSTRE
      FileSystemTypeVersion: 2.12
      LustreConfiguration: 
        AutoImportPolicy: NONE
        DataCompressionType: NONE
        DeploymentType: SCRATCH_1
        ImportPath: !Sub "s3://${Bucket}/"
      SecurityGroupIds: 
        - !Ref FSxSecurityGroup
      StorageCapacity: !Ref FSxStorageCapacity
      StorageType: SSD
      SubnetIds: 
        - !Ref FSxSubnet
