AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String


Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Prefix}-queue"

      
Outputs:
  QueueArn:
    Value: !GetAtt Queue.Arn
    
  QueueUrl:
    Value: !Ref Queue
