AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
    Default: saa-01-002
    
  ServiceName:
    Type: String
    Default: service2
    
  ServiceCpu:
    Type: Number
    Default: 512
    
  ServiceMemory:
    Type: Number
    Default: 1024
    

Resources:
  Cluster2:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${Prefix}-${ServiceName}-cluster

  TaskDefinition2:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref ServiceCpu
      Memory: !Ref ServiceMemory
      NetworkMode: awsvpc
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${Prefix}-FargateTaskExecutionRole
      TaskRoleArn: !Ref TaskRole2
      ContainerDefinitions:
        - Name: !Sub ${Prefix}-${ServiceName}-container
          Image: !Sub
            - ${AccountId}.dkr.ecr.${Region}.amazonaws.com/${RepositoryName}:latest 
            - AccountId: !Ref AWS::AccountId
              Region: !Ref AWS::Region
              RepositoryName:
                Fn::ImportValue: !Sub ${Prefix}-Service2RepositoryName
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Fn::ImportValue: !Sub ${Prefix}-LogGroup2
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: app
          Environment:
            - Name: QueueName
              Value:
                Fn::ImportValue: !Sub ${Prefix}-QueueName
                
  Service2:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster2
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition2
      ServiceName: !Sub ${Prefix}-${ServiceName}
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Fn::ImportValue: !Sub ${Prefix}-ServiceSecurityGroup
          Subnets:
            - Fn::ImportValue: !Sub ${Prefix}-PrivateSubnet2

  TaskRole2:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AllowSQSReceiveMessage
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sqs:GetQueueUrl
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                Resource:
                  - Fn::ImportValue: !Sub ${Prefix}-QueueArn
      
  Service2ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 3
      MinCapacity: 1
      ResourceId: !Select [5, !Split [":", !Ref Service2]]
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      RoleARN: !GetAtt Service2TaskScalingRole.Arn
        
  Service2ScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    DependsOn:
      - Service2
      - Service2ScalableTarget
    Properties: 
      PolicyName: Service2ScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref Service2ScalableTarget
      TargetTrackingScalingPolicyConfiguration: 
        TargetValue: 3
        CustomizedMetricSpecification: 
          Dimensions: 
            - Name: QueueName
              Value:
                Fn::ImportValue: !Sub ${Prefix}-QueueName
          MetricName: ApproximateNumberOfMessagesVisible
          Namespace: AWS/SQS
          Statistic: Average
          Unit: Count
        DisableScaleIn: false
        ScaleInCooldown: 0
        ScaleOutCooldown: 0
      
  Service2TaskScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceAutoscaleRole
