AWSTemplateFormatVersion: 2010-09-09

Parameters:
  HealthCheckIntervalSeconds:
    Type: Number

  HTTPPort:
    Type: Number
    
  Prefix:
    Type: String
    
  Region1:
    Type: String
    
  Region2:
    Type: String
    
  SSMParameterAlbName1:
    Type: String
    
  SSMParameterAlbName2:
    Type: String
    
  ThresholdCount:
    Type: Number
    
  TrafficDialPercentage:
    Type: Number
    

Resources:
  Accelerator:
    Type: AWS::GlobalAccelerator::Accelerator
    Properties:
      Enabled: true
      IpAddressType: IPV4
      Name: !Sub "${Prefix}-accelerator"

  Listener:
    Type: AWS::GlobalAccelerator::Listener
    Properties:
      AcceleratorArn: !Ref Accelerator
      ClientAffinity: NONE
      PortRanges: 
        - FromPort: !Ref HTTPPort
          ToPort: !Ref HTTPPort
      Protocol: TCP
      
  EndpointGroup1:
    Type: AWS::GlobalAccelerator::EndpointGroup
    Properties:
      EndpointConfigurations: 
        - EndpointId: !Sub "{{resolve:ssm:${SSMParameterAlbName1}}}"
      EndpointGroupRegion: !Ref Region1
      HealthCheckIntervalSeconds: !Ref HealthCheckIntervalSeconds
      HealthCheckPort: !Ref HTTPPort
      HealthCheckProtocol: TCP
      ListenerArn: !Ref Listener
      ThresholdCount: !Ref ThresholdCount
      TrafficDialPercentage: !Ref TrafficDialPercentage
      
  EndpointGroup2:
    Type: AWS::GlobalAccelerator::EndpointGroup
    Properties:
      EndpointConfigurations: 
        - EndpointId: !Sub "{{resolve:ssm:${SSMParameterAlbName2}}}"
      EndpointGroupRegion: !Ref Region2
      HealthCheckIntervalSeconds: !Ref HealthCheckIntervalSeconds
      HealthCheckPort: !Ref HTTPPort
      HealthCheckProtocol: TCP
      ListenerArn: !Ref Listener
      ThresholdCount: !Ref ThresholdCount
      TrafficDialPercentage: !Ref TrafficDialPercentage
