AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AvailabilityZone:
    Type: String
    
  DBAllocatedStorage:
    Type: Number
    
  DBEngine:
    Type: String
    
  DBEngineVersion:
    Type: String
    
  DBInstanceClass:
    Type: String
    
  DBName:
    Type: String
    
  DBMasterUsername:
    Type: String
    
  DBMasterUserPassword:
    Type: String
    
  #DBSecurityGroup:
  #  Type: String
    
  DBSubnet1:
    Type: String
    
  DBSubnet2:
    Type: String
    
  Port:
    Type: Number
    
  Prefix:
    Type: String
    
  SourceDBInstanceIdentifier:
    Type: String
    
  SourceDBInstanceRegion:
    Type: String
    
  VPC:
    Type: String
    
    
Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: dbsubnetgroup
      DBSubnetGroupDescription: test subnet group
      SubnetIds:
        - !Ref DBSubnet1
        - !Ref DBSubnet2
        
  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      #AllocatedStorage: !Ref DBAllocatedStorage
      AvailabilityZone: !Sub "${AWS::Region}${AvailabilityZone}"
      #DBInstanceClass: !Ref DBInstanceClass
      DBInstanceIdentifier: !Sub "${Prefix}-dbinstance"
      #DBName: !Ref DBName
      DBSubnetGroupName: !Ref DBSubnetGroup
      #Engine: !Ref DBEngine
      #EngineVersion: !Ref DBEngineVersion
      #MasterUsername: !Ref DBMasterUsername
      #MasterUserPassword: !Ref DBMasterUserPassword
      SourceDBInstanceIdentifier: !Sub "arn:aws:rds:${SourceDBInstanceRegion}:${AWS::AccountId}:db:${SourceDBInstanceIdentifier}"
      #VPCSecurityGroups:
      #  - !Ref DBSecurityGroup
  

Outputs:
  DBInstance:
    Value: !Ref DBInstance