AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
    Default: saa-01-002
    

Resources:
  LogGroup1:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Sub ${Prefix}-LogGroup1

  LogGroup2:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Sub ${Prefix}-LogGroup2
      
  CloudWatchLogsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${Prefix}-EndpointSecurityGroup
      ServiceName: !Sub com.amazonaws.${AWS::Region}.logs
      SubnetIds:
        - Fn::ImportValue: !Sub ${Prefix}-PrivateSubnet1
        - Fn::ImportValue: !Sub ${Prefix}-PrivateSubnet2
      VpcEndpointType: Interface
      VpcId:
        Fn::ImportValue: !Sub ${Prefix}-VPC
      

Outputs:
  LogGroup1:
    Value: !Ref LogGroup1
    Export:
      Name: !Sub ${Prefix}-LogGroup1
      
  LogGroup2:
    Value: !Ref LogGroup2
    Export:
      Name: !Sub ${Prefix}-LogGroup2
