AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ALBDnsName:
    Type: String
    
  ALBHostedZoneId:
    Type: String
    
  DomainName:
    Type: String
    
  FailureThreshold:
    Type: Number
    
  RequestInterval:
    Type: Number
    
  HTTPPort:
    Type: Number
    
  S3DnsName:
    Type: String
    
  S3HostedZoneId:
    Type: String
    

Resources:
  DnsHealthCheck:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Port: !Ref HTTPPort
        Type: HTTP
        ResourcePath: /
        FullyQualifiedDomainName: !Ref ALBDnsName
        RequestInterval: !Ref RequestInterval
        FailureThreshold: !Ref FailureThreshold

  AwstutNetDnsRecordGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      RecordSets:
        # ALB
        - Name: !Ref DomainName
          Failover: PRIMARY
          HealthCheckId: !Ref DnsHealthCheck
          SetIdentifier: primary
          Type: A
          AliasTarget: 
            DNSName: !Ref ALBDnsName
            EvaluateTargetHealth: true
            HostedZoneId: !Ref ALBHostedZoneId
        # S3
        - Name: !Ref DomainName
          Failover: SECONDARY
          SetIdentifier: secondary
          Type: A
          AliasTarget: 
            DNSName: !Ref S3DnsName
            HostedZoneId: !Ref S3HostedZoneId
