AWSTemplateFormatVersion: 2010-09-09

Parameters:
  PrivateRouteTable:
    Type: String

  VPC:
    Type: String
    

Resources:
  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      RouteTableIds:
        - !Ref PrivateRouteTable
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"
      VpcId: !Ref VPC
