AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Prefix:
    Type: String
    Default: saa-03-02
    
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: MyKeyPair
    
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    
    
Resources:
  PublicInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t3.nano
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId:
            Fn::ImportValue: !Sub ${Prefix}-PublicSubnet
          GroupSet:
            - !Ref PublicInstanceSecurityGroup
            
            
  PublicInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: instance-sg
      GroupDescription: Allow ICMP and SSH.
      VpcId:
        Fn::ImportValue: !Sub ${Prefix}-VPC
      SecurityGroupIngress:
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22 
          ToPort: 22 
          CidrIp: 0.0.0.0/0


Outputs:
  PublicInstanceSecurityGroup:
    Value: !Ref PublicInstanceSecurityGroup
    Export:
      Name: !Sub ${Prefix}-PublicInstanceSecurityGroup
