AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Instance1:
    Type: String
    
  Instance2:
    Type: String
    
  MSAD:
    Type: String
    
  MSADDnsIpAddress1:
    Type: String
    
  MSADDnsIpAddress2:
    Type: String
    
  MSADName:
    Type: String
    
  Prefix:
    Type: String
    
  #SSMLogBucket:
  #  Type: String
    
  WaitForSuccessTimeoutSeconds:
    Type: Number
    

Resources:
  AWSJoinDirectoryServiceDomainAssociation:
    Type: AWS::SSM::Association
    Properties:
      AssociationName: !Sub "${Prefix}-aws-join-directory-service-domain-association"
      Name: AWS-JoinDirectoryServiceDomain
      Parameters:
        directoryId:
          - !Ref MSAD
        directoryName:
          - !Ref MSADName
        dnsIpAddresses:
          - !Ref MSADDnsIpAddress1
          - !Ref MSADDnsIpAddress2
      Targets:
        - Key: InstanceIds
          Values:
            - !Ref Instance1
            - !Ref Instance2
      WaitForSuccessTimeoutSeconds: !Ref WaitForSuccessTimeoutSeconds