AWSTemplateFormatVersion: 2010-09-09

Parameters:
  FSxSecurityGroup:
    Type: String
    
  #MSADName:
  #  Type: String
  MSAD:
    Type: String
    
  #Prefix:
  #  Type: String
    
  PrivateSubnet1:
    Type: String
    
  PrivateSubnet2:
    Type: String
    
  StorageCapacity:
    Type: Number
    
  ThroughputCapacity:
    Type: Number


Resources:
  FSxForWindows:
    Type: AWS::FSx::FileSystem
    Properties: 
      FileSystemType: WINDOWS
      SecurityGroupIds: 
        - !Ref FSxSecurityGroup
      StorageCapacity: !Ref StorageCapacity
      StorageType: SSD
      SubnetIds: 
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      WindowsConfiguration: 
        #ActiveDirectoryId: !Ref MSADName
        ActiveDirectoryId: !Ref MSAD
        DeploymentType: MULTI_AZ_1
        PreferredSubnetId: !Ref PrivateSubnet1
        ThroughputCapacity: !Ref ThroughputCapacity