AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    
  InstanceSecurityGroup:
    Type: String
    
  InstanceType:
    Type: String
    
  Prefix:
    Type: String
    
  PublicSubnet:
    Type: String


Resources:
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      
  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt EIP.AllocationId
      InstanceId: !Ref Instance
      
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      #IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        #- AssociatePublicIpAddress: true
        - DeviceIndex: 0
          SubnetId: !Ref PublicSubnet
          GroupSet:
            - !Ref InstanceSecurityGroup
      UserData: !Base64 |
        #!/bin/bash -xe
        yum update -y
        yum install -y httpd
        systemctl start httpd
        systemctl enable httpd
        ec2-metadata -i > /var/www/html/index.html
            
  #InstanceProfile:
  #  Type: AWS::IAM::InstanceProfile
  #  Properties:
  #    Path: /
  #    Roles:
  #      - !Ref InstanceRole
  
  #InstanceRole:
  #  Type: AWS::IAM::Role
  #  Properties:
  #    AssumeRolePolicyDocument:
  #      Version: 2012-10-17
  #      Statement:
  #        - Effect: Allow
  #          Action: sts:AssumeRole
  #          Principal:
  #            Service:
  #              - ec2.amazonaws.com
  #    Policies:
  #      - PolicyName: SSMStateManagerPolicy
  #        PolicyDocument:
  #          Version: 2012-10-17
  #          Statement:
  #            - Effect: Allow
  #              Action:
  #                - s3:GetObject
  #                - s3:PutObject
  #                - s3:PutObjectAcl
  #                - s3:ListBucket
  #              Resource:
  #                - !Sub
  #                  - ${S3Bucket}
  #                  - S3Bucket:
  #                      Fn::ImportValue: !Sub ${Prefix}-S3BucketArn
  #                - !Sub
  #                  - ${S3Bucket}/*
  #                  - S3Bucket:
  #                      Fn::ImportValue: !Sub ${Prefix}-S3BucketArn
  #    ManagedPolicyArns:
  #      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
            
            
Outputs:
  #Instance:
  #  Value: !Ref Instance
      
  InstancePublicDnsName:
    Value: !GetAtt Instance.PublicDnsName