AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
    Default: saa-02-04


Resources:
  EBS:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone:
        Fn::ImportValue: !Sub ${Prefix}-AZ
      Size: 1
      VolumeType: gp3
      
  EBSAttachment:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      Device: /dev/sdf
      InstanceId:
        Fn::ImportValue: !Sub ${Prefix}-PublicInstance1
      VolumeId: !Ref EBS
