AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TemplateBucketName:
    Type: String
    Default: [bucket-name]
    
  TemplateBucketRegion:
    Type: String
    Default: ap-northeast-1
    
  TemplateBucketFolder:
    Type: String
    Default: saa-01-003
    
  Prefix:
    Type: String
    Default: saa-01-003-2
    
    
Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${TemplateBucketRegion}.amazonaws.com/${TemplateBucketFolder}/${Prefix}-s3.yaml"
      Parameters:
        Prefix: !Ref Prefix
