AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Prefix:
    Type: String
    Default: saa-01-03


Resources:
  Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Prefix}-bucket1
      AccelerateConfiguration:
        AccelerationStatus: Enabled
      AccessControl: Private
      
  Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Prefix}-bucket2
      AccelerateConfiguration:
        AccelerationStatus: Suspended
      AccessControl: Private
      
  S3BucketPolicy1:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket1
      PolicyDocument:
        Statement:
          Action:
            - s3:GetObject
            - s3:PutObject
          Effect: Allow
          Resource: !Sub arn:aws:s3:::${Bucket1}/*
          Principal: "*"

  S3BucketPolicy2:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket2
      PolicyDocument:
        Statement:
          Action:
            - s3:GetObject
            - s3:PutObject
          Effect: Allow
          Resource: !Sub arn:aws:s3:::${Bucket2}/*
          Principal: "*"
