AWSTemplateFormatVersion: 2010-09-09

Parameters:
  GeoRestrictionLocation:
    Type: String
    
  HTTPPort:
    Type: Number
    
  OriginDomainName:
    Type: String
    
  Prefix:
    Type: String
    

Resources:
  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: !Ref OriginDomainName
          ViewerProtocolPolicy: allow-all
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
        Enabled: true
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: http-only
              HTTPPort: !Ref HTTPPort
            DomainName: !Ref OriginDomainName
            Id: !Ref OriginDomainName
        PriceClass: PriceClass_All
        Restrictions:
          GeoRestriction:
            Locations:
              - !Ref GeoRestrictionLocation
            RestrictionType: whitelist
