AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Prefix:
    Type: String
    Default: saa-02-10
    
  BucketName:
    Type: String
    Default: bucket


Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub ${Prefix}-${BucketName}
      
  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - s3:*
            Resource:
              - !Sub arn:aws:s3:::${Prefix}-${BucketName}
              - !Sub arn:aws:s3:::${Prefix}-${BucketName}/*
      RouteTableIds:
        - Fn::ImportValue: !Sub ${Prefix}-PrivateRouteTable
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcId:
        Fn::ImportValue: !Sub ${Prefix}-VPC
