AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Instance:
    Type: String
  
  #Instance1:
  #  Type: String
  #  
  #Instance2:
  #  Type: String
  
  HTTPPort:
    Type: String

  Prefix:
    Type: String
    
  PrivateSubnet:
    Type: String
    
  #PrivateSubnet2:
  #  Type: String
    
  #UWSGIPort:
  #  Type: Number
    
  VPC:
    Type: String
    
  #HealthyThresholdCount:
  #  Type: Number
  #  
  #UnhealthyThresholdCount:
  #  Type: Number
  #  
  #HealthCheckIntervalSeconds:
  #  Type: Number


Resources:
  NLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${Prefix}-NLB"
      Scheme: internal
      #SecurityGroups:
      #  - Fn::ImportValue: !Sub ${Prefix}-WebSecurityGroup
      Subnets:
        - !Ref PrivateSubnet
        #- !Ref PrivateSubnet2
      Type: network
      
  NLBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${Prefix}-NLBTargetGroup"
      #Protocol: HTTP
      Protocol: TCP
      Port: !Ref HTTPPort
      #TargetGroupAttributes:
      #  - Key: preserve_client_ip.enabled
      #    Value: false
      VpcId: !Ref VPC
      #HealthCheckProtocol: TCP
      #HealthyThresholdCount: !Ref HealthyThresholdCount
      #UnhealthyThresholdCount: !Ref UnhealthyThresholdCount
      #HealthCheckIntervalSeconds: !Ref HealthCheckIntervalSeconds
      Targets:
        - Id: !Ref Instance
        
  NLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions: 
        - TargetGroupArn: !Ref NLBTargetGroup
          Type: forward
      LoadBalancerArn: !Ref NLB
      Port: !Ref HTTPPort
      Protocol: TCP
      
  VPCEndpointService:
    Type: AWS::EC2::VPCEndpointService
    Properties: 
      AcceptanceRequired: false
      #ContributorInsightsEnabled: Boolean
      #GatewayLoadBalancerArns: 
      #  - String
      NetworkLoadBalancerArns: 
        - !Ref NLB
      #PayerResponsibility: String


Outputs:
  VPCEndpointService:
    Value: !Ref VPCEndpointService

  #NLBDNSName:
  #  Value: !GetAtt NLB.DNSName
  #  #Export:
  #  #  Name: !Sub ${Prefix}-ALBDNSName
  #  
  #NLBLoadBalancerName:
  #  Value: !GetAtt NLB.LoadBalancerName
  #    
  #NLBTargetGroup:
  #  Value: !Ref NLBTargetGroup
  #  #Export:
  #  #  Name: !Sub ${Prefix}-NLBTargetGroup