AWSTemplateFormatVersion: 2010-09-09

Parameters:
  HTTPPort:
    Type: Number

  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    
  InstanceSecurityGroup:
    Type: String

  InstanceType:
    Type: String

  Prefix:
    Type: String

  PrivateSubnet:
    Type: String

  VPC:
    Type: String


Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref PrivateSubnet
          GroupSet:
            - !Ref InstanceSecurityGroup
      UserData: !Base64 |
        #!/bin/bash -xe
        yum update -y
        yum install -y httpd
        systemctl start httpd
        systemctl enable httpd
        ec2-metadata -i > /var/www/html/index.html

        
Outputs:
  Instance:
    Value: !Ref Instance
