AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>

  InstanceSecurityGroup:
    Type: String

  InstanceSubnet1:
    Type: String
    
  InstanceSubnet2:
    Type: String
    
  InstanceSubnet3:
    Type: String

  InstanceType:
    Type: String
    

Resources:
  Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref InstanceSubnet1
          GroupSet:
            - !Ref InstanceSecurityGroup
      
  Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref InstanceSubnet2
          GroupSet:
            - !Ref InstanceSecurityGroup
            
  Instance3:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref InstanceSubnet3
          GroupSet:
            - !Ref InstanceSecurityGroup

  
Outputs:
  Instance1:
    Value: !Ref Instance1
    
  Instance2:
    Value: !Ref Instance2
    
  Instance3:
    Value: !Ref Instance3
