AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Instance:
    Type: String

  Prefix:
    Type: String


Resources:
  StartInstanceSchedule:
    Type: AWS::Scheduler::Schedule
    Properties: 
      Description: StartInstance
      FlexibleTimeWindow: 
        Mode: "OFF"
      Name: !Sub "${Prefix}-StartInstanceSchedule"
      ScheduleExpression: cron(0,10,20,30,40,50 * * * ? *)
      State: ENABLED
      Target: 
        Arn: arn:aws:scheduler:::aws-sdk:ec2:startInstances
        Input: !Sub '{"InstanceIds": ["${Instance}"]}'
        RoleArn: !GetAtt SchedulerRole.Arn
        
  StopInstanceSchedule:
    Type: AWS::Scheduler::Schedule
    Properties: 
      Description: StopInstance
      FlexibleTimeWindow: 
        Mode: "OFF"
      Name: !Sub "${Prefix}-StopInstanceSchedule"
      ScheduleExpression: cron(5,15,25,35,45,55 * * * ? *)
      State: ENABLED
      Target: 
        Arn: arn:aws:scheduler:::aws-sdk:ec2:stopInstances
        Input: !Sub '{"InstanceIds": ["${Instance}"]}'
        RoleArn: !GetAtt SchedulerRole.Arn

  SchedulerRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - scheduler.amazonaws.com
      Policies:
        - PolicyName: CreateImagePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:StartInstances
                  - ec2:StopInstances
                Resource: !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/${Instance}"
