AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TemplateBucketName:
    Type: String
    Default: awstut-bucket
    
  Prefix:
    Type: String
    Default: saa-04-004

  AvailabilityZone1:
    Type: String
    Default: a
    
  AvailabilityZone2:
    Type: String
    Default: c
    
  AvailabilityZone3:
    Type: String
    Default: d
    
  #DBEngine:
  #  Type: String
  #  Default: aurora-mysql
  #  
  #DBEngineVersion:
  #  Type: String
  #  Default: 8.0.mysql_aurora.3.03.1
  #  
  #DBInstanceClass:
  #  Type: String
  #  Default: db.serverless
  #  
  #DBName:
  #  Type: String
  #  Default: testdb
  #  
  #DBMasterUsername:
  #  Type: String
  #  Default: testuser
  #  
  #DBMasterUserPassword:
  #  Type: String
  #  Default: Passw0rd
    
  #HTTPSPort:
  #  Type: Number
  #  Default: 443
    
  InstanceImageId:
    Type: String
    #Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-arm64-gp2
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-arm64
    
  #InstanceTagKey:
  #  Type: String
  #  Default: schedule
  #  
  #InstanceTagValue:
  #  Type: String
  #  Default: true
    
  InstanceType:
    Type: String
    Default: t4g.nano
    
  LambdaArchitecture:
    Type: String
    Default: arm64
    
  LambdaHandler:
    Type: String
    Default: index.lambda_handler
    
  LambdaRuntime:
    Type: String
    Default: python3.8
    
  LambdaTimeout:
    Type: Number
    Default: 10
    
  #MySQLPort:
  #  Type: Number
  #  Default: 3306
    
    
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-vpc.yaml"
      Parameters:
        AvailabilityZone1: !Ref AvailabilityZone1
        AvailabilityZone2: !Ref AvailabilityZone2
        AvailabilityZone3: !Ref AvailabilityZone3
        CidrIp1: 10.0.1.0/24
        CidrIp2: 10.0.2.0/24
        CidrIp3: 10.0.3.0/24
        #HTTPSPort: !Ref HTTPSPort
        #MySQLPort: !Ref MySQLPort
        Prefix: !Ref Prefix
        VPCCidrBlock: 10.0.0.0/16
        
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-ec2.yaml"
      Parameters:
        ImageId: !Ref InstanceImageId
        InstanceSecurityGroup: !GetAtt VPCStack.Outputs.InstanceSecurityGroup
        InstanceSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        InstanceSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        InstanceSubnet3: !GetAtt VPCStack.Outputs.PrivateSubnet3
        #InstanceTagKey: !Ref InstanceTagKey
        #InstanceTagValue: !Ref InstanceTagValue
        InstanceType: !Ref InstanceType
        
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - EC2Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-lambda.yaml"
      Parameters:
        Architecture: !Ref LambdaArchitecture
        #CodeS3Bucket: !GetAtt S3Bucket.Outputs.Bucket
        #CodeS3Bucket: !Ref TemplateBucketName
        #CodeS3Key: !Sub "${Prefix}/${LambdaPackage}"
        #EphemeralStorageSize: !Ref EphemeralStorageSize
        #FunctionSecurityGroup: !GetAtt VPCStack.Outputs.FunctionSecurityGroup
        Handler: !Ref LambdaHandler
        Instance: !GetAtt EC2Stack.Outputs.Instance1
        #LayerPackage: !Ref LayerPackage
        #LayerS3Key: !Sub "${Prefix}/${LayerPackage}"
        Prefix: !Ref Prefix
        Runtime: !Ref LambdaRuntime
        Timeout: !Ref LambdaTimeout
        #UrlsParameter: !GetAtt SSMStack.Outputs.UrlsParameter
        
  SSMStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - EC2Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-ssm.yaml"
      Parameters:
        Instance: !GetAtt EC2Stack.Outputs.Instance2
        Prefix: !Ref Prefix
        
  EventBridgeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - EC2Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/${Prefix}/${Prefix}-eventbridge.yaml"
      Parameters:
        Instance: !GetAtt EC2Stack.Outputs.Instance3
        #InstanceTagKey: !Ref InstanceTagKey
        #InstanceTagValue: !Ref InstanceTagValue
        Prefix: !Ref Prefix