AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ALBHostedZoneId1:
    Type: String
    
  ALBHostedZoneId2:
    Type: String

  DomainName:
    Type: String

  Region1:
    Type: String
    
  Region2:
    Type: String

  SSMParameterALBDNSName1:
    Type: String
    
  SSMParameterALBDNSName2:
    Type: String


Resources:
  RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      RecordSets: 
        - AliasTarget: 
            DNSName: !Sub "{{resolve:ssm:${SSMParameterALBDNSName1}}}"
            HostedZoneId: !Ref ALBHostedZoneId1
          GeoLocation: 
            ContinentCode: AS
          Name: !Ref DomainName
          SetIdentifier: !Ref Region1
          Type: A
        - AliasTarget: 
            DNSName: !Sub "{{resolve:ssm:${SSMParameterALBDNSName2}}}"
            HostedZoneId: !Ref ALBHostedZoneId2
          GeoLocation: 
            ContinentCode: NA
          Name: !Ref DomainName
          SetIdentifier: !Ref Region2
          Type: A
