AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
    
  ReadCapacityUnits:
    Type: Number
    
  WriteCapacityUnits:
    Type: Number


Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: partition_key
          AttributeType: N
        - AttributeName: sort_key
          AttributeType: N
      BillingMode: PROVISIONED
      KeySchema:
        - AttributeName: partition_key
          KeyType: HASH
        - AttributeName: sort_key
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits
      TableClass: STANDARD
      TableName: TryDaxTable


Outputs:
  Table:
    Value: !Ref Table
  
  TableArn:
    Value: !GetAtt Table.Arn
