AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Prefix:
    Type: String
    Default: saa-02-05
    
  IndexDocument:
    Type: String
    Default:  index.html


Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Prefix}-bucket
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: !Ref IndexDocument
        
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Action:
            - s3:GetObject
          Effect: Allow
          Principal: "*"
          Resource: !Sub
            - arn:aws:s3:::${BucketName}/*
            - BucketName: !Ref Bucket


Outputs:
  BucketName:
    Value: !Ref Bucket
    Export:
      Name: !Sub ${Prefix}-BucketName
      
  DomainName:
    Value: !GetAtt Bucket.DomainName
    Export:
      Name: !Sub ${Prefix}-DomainName
      
  IndexDocument:
    Value: !Ref IndexDocument
    Export:
      Name: !Sub ${Prefix}-IndexDocument
